### ISSUE TITLE
Incompatibility between 1.12.0 and earlier version(s)

### ISSUE THREAD

**Issue by LukasWieditz** [paragonie/sodium_compat#107]
It appears there is an incompatibility between the latest version of the library and earlier versions, where, if an earlier version is loaded first, the checks performed by the library will not suffice to detect this, and attempt to load elements anew.

The specific issue at hand is caused by a WordPress plugin connecting to a different software that utilizes the latest version of the library, causing WordPress to emit notices and thus breaking the page output:
![7bTCTBz](https://user-images.githubusercontent.com/38475165/68383830-af6a0e80-0156-11ea-878f-ae569694c645.png)

Potentially related to #101

**Comment by paragonie-scott** [comment]
It's almost certainly related to #101. However, I have not succeeded in reproducing the environment causing either their problem nor yours, so I'm not sure how helpful I'll be without a tight information feedback loop. Are you willing to help with troubleshooting this?

If so, the first thing I need to know is:

* Which version of PHP?
* Which version of Windows?
* Is OpCache enabled?
* Does changing line 50 of `sodium_compat/autoload.php` to check for `SODIUM_CRYPTO_SCALARMULT_BYTES` instead of `SODIUM_LIBRARY_MAJOR_VERSION` fix the problem?

**Comment by LukasWieditz** [comment]
> Are you willing to help with troubleshooting this?
Absolutely.

> Which version of PHP?
7.1.8
> Which version of Windows?
W10 Pro Version 1809, Build 17763.805

> Is OpCache enabled?
No, not enabled.

> Does changing line 50 of sodium_compat/autoload.php to check for SODIUM_CRYPTO_SCALARMULT_BYTES instead of SODIUM_LIBRARY_MAJOR_VERSION fix the problem?
Yes it does.

**Comment by paragonie-scott** [comment]
...Interesting! Well, if that easy fix does it, I'm happy with that.

**Comment by paragonie-scott** [comment]
Fix landed in `v1.12.1`, I'll also update the WordPress ticket.

**Comment by paragonie-scott** [comment]
https://core.trac.wordpress.org/ticket/48371#comment:5 Thanks for reporting this and your help with confirming my suspicions about a quick fix. 👍
