### ISSUE TITLE
suggests ext-sodium

### ISSUE THREAD

**Issue by pmsteil** [paragonie/sodium_compat#126]
Hello, thanks for any help here...  I see this in the suggests for this composer package:

`ext-sodium: PHP >= 7.0: Better performance, password hashing (Argon2i), secure memory management (memzero), and better security.`

But composer won't let me install with

```
composer require paragonie/ext-sodium
```
or
```
composer require ext/sodium
```

And I don't see this ext-sodium library anywhere?  What am I missing?

I am running on Magento 2.4.1/2.4.2 with PHP 7.4.11 and getting this error:

```
"0": "This is not implemented, as it is not possible to implement Argon2i with acceptable performance in pure-PHP",
"1": "#1 sodium_crypto_pwhash() called at [vendor/magento/framework/Encryption/Encryptor.php:594]
```

Thanks!

**Comment by aidantwoods** [comment]
Hi @pmsteil,

`ext-sodium` is a PHP extension (rather than a composer package), info on enabling it here: https://www.php.net/manual/en/sodium.installation.php.

The reason it's an extension, rather than a composer package written in PHP, is actually part of the error message: it's not practical to implement in PHP due to performance constraints. 

P.S. In general, when reading composer requirements anything with an `ext-` prefix refers to a PHP extension (rather than a composer package). 

Hope that helps! :)

**Comment by pmsteil** [comment]
@aidantwoods - ok thanks!
