### ISSUE TITLE
crypto_pwhash_* methods

### ISSUE THREAD

**Issue by Lavoaster** [paragonie/sodium_compat#36]
I was hoping to use the 7.2 style syntax for these methods, but they aren't provided in here. Is there any chance of bringing them in like `memzero`, where they throw an exception on default php?

On the same note, would that mean all methods would appear in this library? (Are these the only missing ones?)

**Comment by paragonie-scott** [comment]
That's easily arranged. I was originally working on a polyfill in other branches, but they were not performant enough (e.g. MEMLIMIT_INTERACTIVE + OPSLIMIT_INTERACTIVE -> didn't complete after several hours). [For example](https://github.com/paragonie/sodium_compat/tree/scrypt).

I hadn't implemented the fall-throughs because I was hoping that I was making some dumb error and there was actually a clever trick that would make it work, but I've sort of given up on that ever happening. Best to wait until PHP 7.2.

When I'll release v1.1.0, it will have these methods added (but like `memzero` it will only error out).

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/sodium_compat/commit/43b7dd2e2323d1a3902f7cd49846d241969557c0 

`v1.1.0` coming.

**Comment by Lavoaster** [comment]
❤️ Thanks @paragonie-scott
